repos:
  - repo: https://github.com/PyCQA/isort
    rev: stable
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: stable
    hooks:
      - id: flake8
